=== Bjoern-Hegstam/physicalia/PhysicaliaRemastered/Content/GameData/Schemas/schema_textureLibrary.xsd
<?xml version="1.0" encoding="utf-8"?>

<!-- Created with Liquid XML Studio 1.0.8.0 (http://www.liquid-technologies.com) -->
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="TextureLibrary">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="1" name="Textures">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element minOccurs="1" maxOccurs="unbounded" name="Texture">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="id" type="xs:int" />
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Bjoern-Hegstam/physicalia/PhysicaliaRemastered/Content/GameData/Libraries/TextureLibrary.xml
<?xml version="1.0" encoding="utf-8"?>
<TextureLibrary xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../Schemas/schema_textureLibrary.xsd">
	<Textures>
		<!-- Tiles 0x -->
		<Texture id="0">Content\GameData\Graphics\tiles_Grass_Earth.png</Texture>
		<Texture id="1">Content\GameData\Graphics\tiles_mechanical.png</Texture>
		<Texture id="2">Content\GameData\Graphics\tiles_schoolSet.png</Texture>
		
		<!-- Weapons 1x -->
		<Texture id="10">Content\GameData\Graphics\weaponSheet.png</Texture>
		<Texture id="11">Content\GameData\Graphics\Weapon_chainsaw.png</Texture>
		<Texture id="12">Content\GameData\Graphics\Weapon_minigun.png</Texture>
		
		<!-- Player sprites and UI 2x -->
		<Texture id="20">Content\GameData\Graphics\player_spritesheet.png</Texture>
		<Texture id="21">Content\GameData\Graphics\ui_healthBars.png</Texture>
		
		<!-- Enemies 3x -->
		<Texture id="30">Content\GameData\Graphics\enemy_passare.png</Texture>
		
		<!-- Pickups 1xx -->
		<Texture id="100">Content\GameData\Graphics\pickupSheet.png</Texture>
		
		<!-- Particles 2xx -->
		<Texture id="200">Content\GameData\Graphics\explode_1.png</Texture>
		
		<!-- Backgrounds 3xx -->
		<Texture id="300">Content\GameData\Graphics\background_sky.png</Texture>
		<Texture id="301">Content\GameData\Graphics\background_mountains.png</Texture>
		<Texture id="302">Content\GameData\Graphics\background_houses.png</Texture>
		<Texture id="303">Content\GameData\Graphics\level2-1_back_1.png</Texture>
		<Texture id="304">Content\GameData\Graphics\level2-1_back_2.png</Texture>
	</Textures>
</TextureLibrary>
