=== Bjoern-Hegstam/physicalia/PhysicaliaRemastered/Content/GameData/Schemas/schema_game.xsd
<?xml version="1.0" encoding="utf-8"?>

<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:include schemaLocation="schema_dataTypes.xsd" />
    <xs:element name="Game">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="TextureLibrary" />
                <xs:element name="SpriteLibrary" />
                <xs:element name="Settings" type="xs:string" />
                <xs:element name="AnimationBank" />
                <xs:element name="TileLibrary" />
                <xs:element name="ParticleDefinitions" />
                <xs:element name="WeaponBank" />
                <xs:element name="EnemyBank" />
                <xs:element name="PickupLibrary" />
                <xs:element name="Player">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="CollisionBox" type="Rectangle" />
                            <xs:element name="Animations">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element minOccurs="1" maxOccurs="unbounded" name="Animation">
                                            <xs:complexType>
                                                <xs:attribute name="key" type="xs:int" />
                                                <xs:attribute name="action" type="xs:int" />
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element minOccurs="1" maxOccurs="1" name="Worlds">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element minOccurs="1" maxOccurs="unbounded" name="World" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Bjoern-Hegstam/physicalia/PhysicaliaRemastered/Content/GameData/Game.xml
<?xml version="1.0" encoding="utf-8"?>

<Game xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Schemas/schema_game.xsd">
    <TextureLibrary>TextureLibrary.xml</TextureLibrary>
    <SpriteLibrary>SpriteLibrary.xml</SpriteLibrary>
    <Settings>Settings.xml</Settings>
    <AnimationLibrary>AnimationLibrary.xml</AnimationLibrary>
    <TileLibrary>TileLibrary.xml</TileLibrary>
    <ParticleDefinitions>ParticleDefinitions.xml</ParticleDefinitions>
    <WeaponLibrary>WeaponLibrary.xml</WeaponLibrary>
    <EnemyLibrary>EnemyLibrary.xml</EnemyLibrary>
    <PickupLibrary>PickupLibrary.xml</PickupLibrary>
    <Player>
        <CollisionBox x="2" y="0" width="18" height="48" />
        <Animations>
            <Animation id="0" action="0" />
            <Animation id="1" action="1" />
            <Animation id="2" action="2" />
            <Animation id="3" action="3" />
            <Animation id="4" action="4" />
            <Animation id="5" action="5" />
        </Animations>
    </Player>
    <Worlds>
        <World>world_1.xml</World>
        <World>world_2.xml</World>
    </Worlds>
</Game>
