=== Bjoern-Hegstam/physicalia/PhysicaliaRemastered/Content/GameData/Schemas/schema_world.xsd
<?xml version="1.0" encoding="utf-8"?>

<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:include schemaLocation="schema_dataTypes.xsd" />
    <xs:element name="World">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Presentation">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="StartSprite">
                                <xs:complexType>
                                    <xs:attribute name="spriteId" type="xs:int" />
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Quote">
                                <xs:complexType mixed="true">
                                    <xs:sequence>
                                        <xs:element minOccurs="0" maxOccurs="unbounded" name="Char" type="xs:string" />
                                        <xs:element minOccurs="0" maxOccurs="unbounded" name="br" />
                                    </xs:sequence>
                                    <xs:attribute name="color" type="ColorType" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Levels">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="Level" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Bjoern-Hegstam/physicalia/PhysicaliaRemastered/Content/GameData/Worlds/world_2.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid XML Studio 1.0.8.0 (http://www.liquid-technologies.com) -->
<World xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../Schemas/schema_world.xsd">
	<Presentation>
		<StartSprite key="0" />
		<Quote color="255 255 255 255">Alpha &amp; Omega</Quote>
	</Presentation>
	<Levels>
		<Level>level_5.xml</Level>
		<Level>level_6.xml</Level>
		<Level>level_7.xml</Level>
	</Levels>
</World>

=== Bjoern-Hegstam/physicalia/PhysicaliaRemastered/Content/GameData/Worlds/world_1.xml
<?xml version="1.0" encoding="utf-8"?>

<World xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="../Schemas/schema_world.xsd">
    <Presentation>
        <StartSprite spriteId="5" />
        <Quote color="255 255 255 255">Cake or Pi?</Quote>
    </Presentation>
    <Levels>
        <Level>player-tile-collision-test.xml</Level>
        <Level>level_2-1.xml</Level>
        <Level>level_2-1--player-only.xml</Level>
        <Level>level_2.xml</Level>
        <Level>level_1.xml</Level>
        <Level>level_4.xml</Level>
    </Levels>
</World>
