=== Bjoern-Hegstam/physicalia/PhysicaliaRemastered/Content/GameData/Schemas/schema_animationBank.xsd
<?xml version="1.0" encoding="utf-8"?>

<!-- Created with Liquid XML Studio 1.0.8.0 (http://www.liquid-technologies.com) -->
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:include schemaLocation="schema_dataTypes.xsd" />
    <xs:element name="AnimationBank">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="1" name="Animations">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element minOccurs="1" maxOccurs="unbounded" name="Animation">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="TextureKey" type="xs:int" />
                                        <xs:element name="StartFrame" type="Rectangle" />
                                        <xs:element name="Dimensions">
                                            <xs:complexType>
                                                <xs:attribute name="columns" type="xs:int" />
                                                <xs:attribute name="rows" type="xs:int" />
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="FrameRate" type="xs:int" />
                                        <xs:element name="Loop" type="xs:boolean" />
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:int" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Bjoern-Hegstam/physicalia/PhysicaliaRemastered/Content/GameData/Libraries/AnimationBank.xml
<?xml version="1.0" encoding="utf-8"?>
<AnimationBank  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../Schemas/schema_animationBank.xsd">
	<Animations>
		<!-- Player -->
		<Animation id="0">
			<TextureKey>20</TextureKey>
			<StartFrame x="0" y="0" width="32" height="48" />
			<Dimensions columns="1" rows="1" />
			<FrameRate>0</FrameRate>
			<Loop>true</Loop>
		</Animation>
		<Animation id="1">
			<TextureKey>20</TextureKey>
			<StartFrame x="0" y="48" width="32" height="48" />
			<Dimensions columns="4" rows="1" />
			<FrameRate>5</FrameRate>
			<Loop>true</Loop>
		</Animation>
		<Animation id="2">
			<TextureKey>20</TextureKey>
			<StartFrame x="0" y="96" width="32" height="48" />
			<Dimensions columns="2" rows="1" />
			<FrameRate>4</FrameRate>
			<Loop>true</Loop>
		</Animation>
		<Animation id="3">
			<TextureKey>20</TextureKey>
			<StartFrame x="0" y="144" width="32" height="48" />
			<Dimensions columns="2" rows="1" />
			<FrameRate>4</FrameRate>
			<Loop>true</Loop>
		</Animation>
		<Animation id="4">
			<TextureKey>20</TextureKey>
			<StartFrame x="0" y="192" width="32" height="48" />
			<Dimensions columns="2" rows="1" />
			<FrameRate>4</FrameRate>
			<Loop>false</Loop>
		</Animation>
		<Animation id="5">
			<TextureKey>20</TextureKey>
			<StartFrame x="0" y="240" width="32" height="48" />
			<Dimensions columns="2" rows="1" />
			<FrameRate>5</FrameRate>
			<Loop>true</Loop>
		</Animation>
		
		<!-- Weapon Arms-->
		<Animation id="21">
			<TextureKey>10</TextureKey>
			<StartFrame x="0" y="0" width="64" height="48" />
			<Dimensions columns="1" rows="1" />
			<FrameRate>1</FrameRate>
			<Loop>true</Loop>
		</Animation>
		
		<!-- Weapon Minigun -->
		<Animation id="7">
			<TextureKey>12</TextureKey>
			<StartFrame x="0" y="48" width="64" height="48" />
			<Dimensions columns="4" rows="1" />
			<FrameRate>15</FrameRate>
			<Loop>true</Loop>
		</Animation>
		<Animation id="9">
			<TextureKey>12</TextureKey>
			<StartFrame x="0" y="0" width="64" height="48" />
			<Dimensions columns="4" rows="1" />
			<FrameRate>25</FrameRate>
			<Loop>true</Loop>
		</Animation>
		
		<!-- Weapon Chainsaw -->
		<Animation id="8">
			<TextureKey>11</TextureKey>
			<StartFrame x="0" y="0" width="64" height="48" />
			<Dimensions columns="2" rows="1" />
			<FrameRate>5</FrameRate>
			<Loop>true</Loop>
		</Animation>
		
		<!-- Enemy Passare-->
		<Animation id="10">
			<TextureKey>30</TextureKey>
			<StartFrame x="0" y="0" width="48" height="91" />
			<Dimensions columns="8" rows="1" />
			<FrameRate>7</FrameRate>
			<Loop>true</Loop>
		</Animation>
		<Animation id="11">
			<TextureKey>30</TextureKey>
			<StartFrame x="0" y="91" width="48" height="91" />
			<Dimensions columns="4" rows="1" />
			<FrameRate>10</FrameRate>
			<Loop>true</Loop>
		</Animation>
		<Animation id="12">
			<TextureKey>30</TextureKey>
			<StartFrame x="0" y="182" width="48" height="91" />
			<Dimensions columns="2" rows="1" />
			<FrameRate>7</FrameRate>
			<Loop>true</Loop>
		</Animation>
		<Animation id="13">
			<TextureKey>30</TextureKey>
			<StartFrame x="0" y="273" width="48" height="91" />
			<Dimensions columns="4" rows="1" />
			<FrameRate>7</FrameRate>
			<Loop>false</Loop>
		</Animation>
		
		<!-- Explosions -->
		<Animation id="42">
			<TextureKey>200</TextureKey>
			<StartFrame x="0" y="0" width="64" height="64" />
			<Dimensions columns="4" rows="4" />
			<FrameRate>15</FrameRate>
			<Loop>false</Loop>
		</Animation>
	</Animations>
</AnimationBank>
