=== Bjoern-Hegstam/physicalia/PhysicaliaRemastered/Content/GameData/Schemas/schema_spriteLibrary.xsd
<?xml version="1.0" encoding="utf-8"?>

<!-- Created with Liquid XML Studio 1.0.8.0 (http://www.liquid-technologies.com) -->
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="SpriteLibrary">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="1" name="Sprites">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element minOccurs="0" maxOccurs="unbounded" name="Sprite">
                                <xs:complexType>
                                    <xs:attribute name="id" type="xs:int" />
                                    <xs:attribute name="textureKey" type="xs:int" />
                                    <xs:attribute name="x" type="xs:int" />
                                    <xs:attribute name="y" type="xs:int" />
                                    <xs:attribute name="width" type="xs:int" />
                                    <xs:attribute name="height" type="xs:int" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Bjoern-Hegstam/physicalia/PhysicaliaRemastered/Content/TEMP/SpriteLibrary.xml
<?xml version="1.0" encoding="utf-8"?>

<!-- Created with Liquid XML Studio 1.0.7.0 (http://www.liquid-technologies.com) -->
<SpriteLibrary xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:noNamespaceSchemaLocation="file:///C:/Documents%20and%20Settings/bjorn.hegstam/Mina%20dokument/Texter/Projekt/Physicalia/Xml/schema_SpriteLibrary.xsd">
    <Textures>
        <Texture id="0">C:\Documents and Settings\bjorn.hegstam\Mina dokument\Mina bilder\Physicalia_Graphics\Images\Tilesheets\tiles_Grass_Earth.png</Texture>
    </Textures>
    <Sprites>
        <Sprite id="0" textureKey="0" x="0" y="0" width="32" height="32" />
        <Sprite id="1" textureKey="0" x="32" y="0" width="32" height="32" />
        <Sprite id="2" textureKey="0" x="64" y="0" width="32" height="32" />
        <Sprite id="3" textureKey="0" x="0" y="32" width="32" height="32" />
        <Sprite id="4" textureKey="0" x="32" y="32" width="32" height="32" />
        <Sprite id="5" textureKey="0" x="64" y="32" width="32" height="32" />
        <Sprite id="6" textureKey="0" x="0" y="64" width="32" height="32" />
        <Sprite id="7" textureKey="0" x="32" y="64" width="32" height="32" />
        <Sprite id="8" textureKey="0" x="64" y="64" width="32" height="32" />
    </Sprites>
</SpriteLibrary>

=== Bjoern-Hegstam/physicalia/PhysicaliaRemastered/Content/GameData/Libraries/SpriteLibrary.xml
<?xml version="1.0" encoding="utf-8"?>

<SpriteLibrary xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:noNamespaceSchemaLocation="../Schemas/schema_spriteLibrary.xsd">
    <Sprites>
        <!-- EndLevelTrigger sprite -->
        <Sprite id="-1" textureId="GameData/Graphics/pickupSheet" x="0" y="0" width="48" height="48" />

        <!-- UI -->
        <Sprite id="-2" textureId="GameData/Graphics/ui_healthBars" x="0" y="0" width="172" height="48" />
        <Sprite id="-3" textureId="GameData/Graphics/ui_healthBars" x="0" y="48" width="172" height="48" />

        <!-- Tiles Grass -->
        <Sprite id="0" textureId="GameData/Graphics/tiles_Grass_Earth" x="0" y="0" width="32" height="32" />
        <Sprite id="1" textureId="GameData/Graphics/tiles_Grass_Earth" x="32" y="0" width="32" height="32" />
        <Sprite id="2" textureId="GameData/Graphics/tiles_Grass_Earth" x="64" y="0" width="32" height="32" />
        <Sprite id="3" textureId="GameData/Graphics/tiles_Grass_Earth" x="0" y="32" width="32" height="32" />
        <Sprite id="4" textureId="GameData/Graphics/tiles_Grass_Earth" x="32" y="32" width="32" height="32" />
        <Sprite id="5" textureId="GameData/Graphics/tiles_Grass_Earth" x="64" y="32" width="32" height="32" />
        <Sprite id="6" textureId="GameData/Graphics/tiles_Grass_Earth" x="0" y="64" width="32" height="32" />
        <Sprite id="7" textureId="GameData/Graphics/tiles_Grass_Earth" x="32" y="64" width="32" height="32" />
        <Sprite id="8" textureId="GameData/Graphics/tiles_Grass_Earth" x="64" y="64" width="32" height="32" />

        <!-- Tiles Grass Upside down-->
        <Sprite id="20" textureId="GameData/Graphics/tiles_Grass_Earth" x="0" y="96" width="32" height="32" />
        <Sprite id="21" textureId="GameData/Graphics/tiles_Grass_Earth" x="32" y="96" width="32" height="32" />
        <Sprite id="22" textureId="GameData/Graphics/tiles_Grass_Earth" x="64" y="96" width="32" height="32" />
        <Sprite id="23" textureId="GameData/Graphics/tiles_Grass_Earth" x="0" y="128" width="32" height="32" />
        <Sprite id="24" textureId="GameData/Graphics/tiles_Grass_Earth" x="32" y="128" width="32" height="32" />
        <Sprite id="25" textureId="GameData/Graphics/tiles_Grass_Earth" x="64" y="128" width="32" height="32" />
        <Sprite id="26" textureId="GameData/Graphics/tiles_Grass_Earth" x="0" y="160" width="32" height="32" />
        <Sprite id="27" textureId="GameData/Graphics/tiles_Grass_Earth" x="32" y="160" width="32" height="32" />
        <Sprite id="28" textureId="GameData/Graphics/tiles_Grass_Earth" x="64" y="160" width="32" height="32" />

        <!-- Tiles Mechanical -->
        <Sprite id="10" textureId="GameData/Graphics/tiles_mechanical" x="0" y="0" width="32" height="32" />
        <Sprite id="11" textureId="GameData/Graphics/tiles_mechanical" x="32" y="0" width="32" height="32" />
        <Sprite id="12" textureId="GameData/Graphics/tiles_mechanical" x="64" y="0" width="32" height="32" />
        <Sprite id="13" textureId="GameData/Graphics/tiles_mechanical" x="128" y="0" width="32" height="32" />
        <Sprite id="14" textureId="GameData/Graphics/tiles_mechanical" x="0" y="32" width="32" height="32" />
        <Sprite id="15" textureId="GameData/Graphics/tiles_mechanical" x="32" y="32" width="32" height="32" />
        <Sprite id="16" textureId="GameData/Graphics/tiles_mechanical" x="64" y="32" width="32" height="32" />
        <Sprite id="17" textureId="GameData/Graphics/tiles_mechanical" x="128" y="32" width="32" height="32" />

        <!-- School set -->
        <!-- Interior -->
        <!-- 	Wall Colors -->
        <!-- 		Light Yellow-->
        <Sprite id="30" textureId="GameData/Graphics/tiles_schoolSet" x="32" y="0" width="32" height="32" />

        <!-- 	Straight lines -->
        <!-- 		Vertical -->
        <Sprite id="31" textureId="GameData/Graphics/tiles_schoolSet" x="0" y="0" width="32" height="32" />
        <Sprite id="32" textureId="GameData/Graphics/tiles_schoolSet" x="0" y="32" width="32" height="32" />
        <Sprite id="33" textureId="GameData/Graphics/tiles_schoolSet" x="0" y="64" width="32" height="32" />

        <Sprite id="34" textureId="GameData/Graphics/tiles_schoolSet" x="64" y="0" width="32" height="32" />
        <Sprite id="35" textureId="GameData/Graphics/tiles_schoolSet" x="64" y="32" width="32" height="32" />
        <Sprite id="36" textureId="GameData/Graphics/tiles_schoolSet" x="64" y="64" width="32" height="32" />

        <!-- 		Horizontal -->
        <Sprite id="37" textureId="GameData/Graphics/tiles_schoolSet" x="0" y="160" width="32" height="32" />
        <Sprite id="38" textureId="GameData/Graphics/tiles_schoolSet" x="32" y="160" width="32" height="32" />
        <Sprite id="39" textureId="GameData/Graphics/tiles_schoolSet" x="64" y="160" width="32" height="32" />

        <Sprite id="40" textureId="GameData/Graphics/tiles_schoolSet" x="96" y="96" width="32" height="32" />
        <Sprite id="41" textureId="GameData/Graphics/tiles_schoolSet" x="128" y="96" width="32" height="32" />
        <Sprite id="42" textureId="GameData/Graphics/tiles_schoolSet" x="160" y="96" width="32" height="32" />

        <!-- 	Corners -->
        <Sprite id="43" textureId="GameData/Graphics/tiles_schoolSet" x="32" y="32" width="32" height="32" />
        <Sprite id="44" textureId="GameData/Graphics/tiles_schoolSet" x="32" y="64" width="32" height="32" />

        <Sprite id="45" textureId="GameData/Graphics/tiles_schoolSet" x="0" y="96" width="32" height="32" />
        <Sprite id="46" textureId="GameData/Graphics/tiles_schoolSet" x="32" y="96" width="32" height="32" />

        <Sprite id="47" textureId="GameData/Graphics/tiles_schoolSet" x="0" y="128" width="32" height="32" />
        <Sprite id="48" textureId="GameData/Graphics/tiles_schoolSet" x="32" y="128" width="32" height="32" />

        <!-- Blackboard -->
        <Sprite id="49" textureId="GameData/Graphics/tiles_schoolSet" x="96" y="0" width="32" height="32" />
        <Sprite id="50" textureId="GameData/Graphics/tiles_schoolSet" x="128" y="0" width="32" height="32" />
        <Sprite id="51" textureId="GameData/Graphics/tiles_schoolSet" x="160" y="0" width="32" height="32" />

        <Sprite id="52" textureId="GameData/Graphics/tiles_schoolSet" x="96" y="32" width="32" height="32" />
        <Sprite id="53" textureId="GameData/Graphics/tiles_schoolSet" x="128" y="32" width="32" height="32" />
        <Sprite id="54" textureId="GameData/Graphics/tiles_schoolSet" x="160" y="32" width="32" height="32" />

        <Sprite id="55" textureId="GameData/Graphics/tiles_schoolSet" x="96" y="64" width="32" height="32" />
        <Sprite id="56" textureId="GameData/Graphics/tiles_schoolSet" x="128" y="64" width="32" height="32" />
        <Sprite id="57" textureId="GameData/Graphics/tiles_schoolSet" x="160" y="64" width="32" height="32" />

        <!-- Blackboard decorations -->
        <Sprite id="58" textureId="GameData/Graphics/tiles_schoolSet" x="192" y="0" width="32" height="32" />
        <Sprite id="59" textureId="GameData/Graphics/tiles_schoolSet" x="192" y="32" width="32" height="32" />
        <Sprite id="60" textureId="GameData/Graphics/tiles_schoolSet" x="192" y="64" width="32" height="32" />
        <Sprite id="61" textureId="GameData/Graphics/tiles_schoolSet" x="224" y="0" width="32" height="32" />
        <Sprite id="62" textureId="GameData/Graphics/tiles_schoolSet" x="224" y="32" width="32" height="32" />

        <!-- Door -->
        <Sprite id="63" textureId="GameData/Graphics/tiles_schoolSet" x="96" y="128" width="32" height="32" />
        <Sprite id="64" textureId="GameData/Graphics/tiles_schoolSet" x="96" y="160" width="32" height="32" />

        <!-- Top edges -->
        <Sprite id="65" textureId="GameData/Graphics/tiles_schoolSet" x="128" y="128" width="32" height="32" />
        <Sprite id="66" textureId="GameData/Graphics/tiles_schoolSet" x="160" y="128" width="32" height="32" />
        <Sprite id="67" textureId="GameData/Graphics/tiles_schoolSet" x="192" y="128" width="32" height="32" />

        <Sprite id="68" textureId="GameData/Graphics/tiles_schoolSet" x="128" y="160" width="32" height="32" />
        <Sprite id="69" textureId="GameData/Graphics/tiles_schoolSet" x="160" y="160" width="32" height="32" />

        <!-- Weapon sprites 1xx-->
        <!-- Arms -->
        <Sprite id="100" textureId="GameData/Graphics/weaponSheet" x="0" y="0" width="32" height="13" />
        <!-- Chainsaw -->
        <Sprite id="101" textureId="GameData/Graphics/weaponSheet" x="128" y="49" width="25" height="13" />
        <!-- Minigun -->
        <Sprite id="102" textureId="GameData/Graphics/weaponSheet" x="256" y="97" width="64" height="48" />

        <!-- Particle sprites 2xx -->
        <Sprite id="200" textureId="GameData/Graphics/explode_1" x="10" y="48" width="8" height="2" />

        <!-- Backgrounds 3xx -->
        <Sprite id="300" textureId="GameData/Graphics/background_sky" x="0" y="0" width="640" height="480" />
        <Sprite id="301" textureId="GameData/Graphics/background_mountains" x="0" y="0" width="1600" height="500" />
        <Sprite id="302" textureId="GameData/Graphics/background_houses" x="0" y="0" width="1600" height="528" />
        <Sprite id="303" textureId="GameData/Graphics/level2-1_back_1" x="0" y="0" width="2048" height="960" />
        <Sprite id="304" textureId="GameData/Graphics/level2-1_back_2" x="0" y="0" width="352" height="960" />

        <!-- Pickups 4xx -->
        <Sprite id="400" textureId="GameData/Graphics/pickupSheet" x="48" y="0" width="32" height="32" />
        <Sprite id="401" textureId="GameData/Graphics/pickupSheet" x="80" y="0" width="14" height="14" />
    </Sprites>
</SpriteLibrary>
